export const PRODUCTO_GUARDADO_EXITO = 'PRODUCTO_GUARDADO_EXITO';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const SELECCIONAR_PRODUCTO_EXITO = 'SELECCIONAR_PRODUCTO_EXITO';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const BUSCAR_PRODUCTOS_EXITO = 'BUSCAR_PRODUCTOS_EXITO';




